# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82a935987c8dcab121b2c3858bf8dbe3eafbfb637ddb9742bdbbd2b66ff5a82518945c380ee8b9552336caf24b572fc9e44027e18b1dae697349a57c1c474d37

test:
  secret_key_base: 1c1ff568d481e6e37aa4975df8fc82f6475f45cbaec77cf7c468442a7f351e50d080199d26a8bbde288ed863499be8fbf257b25235d14a4798ca0d85b9389416

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
